apiVersion: v1
kind: Service
metadata:
  name: patroni
  labels:
    app: patroni
spec:
  ports:
    - port: 5432
      name: postgres
    - port: 8008
      name: patroni-api
  clusterIP: None                  
  selector:
    app: patroni