replicaCount: 1
#here replace latest tag with smth like {{tag received from build pipeline}}
image:
  repository: lebonkdoge/mntr
  tag: frontend-ffcf4212ea8a75cae4383370eea0a137da7cac82
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.local
      paths:
        - /
  tls: []

config:
  backendHost: backend
  backendPort: 8080

resources: {}