replicaCount: 1
#here replace latest tag with smth like {{tag received from build pipeline}}
image:
  repository: lebonkdoge/mntr
  tag: frontend-ac8b1b8571b348e8040d1fccb072137e2f929a9d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: frontend.local
      paths:
        - /
  tls: []

config:
  backendHost: backend
  backendPort: 8080

resources: {}