replicaCount: 1

image:
  repository: lebonkdoge/mntr
  tag: backend-latest
  pullPolicy: Always

service:
  port: 8080

env:
  DB_HOST: db
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: testdb

resources: {}