apiVersion: v1
kind: Secret
metadata:
  name: etcd-certs
type: Opaque
data:
  ca.crt: {{ .Values.etcdCerts.ca | b64enc | quote }}
  server.crt: {{ .Values.etcdCerts.cert | b64enc | quote }}
  server.key: {{ .Values.etcdCerts.key | b64enc | quote }}