apiVersion: v1
kind: Secret
metadata:
  name: calico-node-token-manual
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: calico-node
type: kubernetes.io/service-account-token