apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
  
# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
#   namespace: mntr
# spec:
#   type: NodePort
#   selector:
#     app: frontend
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30724 

