apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-patroni-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/pv/db0
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-patroni-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/pv/db1
  storageClassName: hostpath