replicaCount: 1
#here replace latest tag with smth like {{tag received from build pipeline}}
image:
  repository: lebonkdoge/mntr
  tag: backend-da9adc614dbeefb44bd0090d1a7a1c9444512aa6
  pullPolicy: Always

service:
  port: 8080

env:
  DB_HOST: db
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: testdb

resources: {}