replicaCount: 1
#here replace latest tag with smth like {{tag received from build pipeline}}
image:
  repository: lebonkdoge/mntr
  tag: backend-ac8b1b8571b348e8040d1fccb072137e2f929a9d
  pullPolicy: Always

service:
  port: 8080

env:
  DB_HOST: db
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: testdb

resources: {}