name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Lint & Tests 
        run: echo tests tbd

      - name: Docker Hub login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
        run: echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

      - name: Build & Push backend
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ./manifests/backend
          docker build -t $DOCKER_USER/mntr-backend:$IMAGE_TAG .
          docker push $DOCKER_USER/mntr-backend:$IMAGE_TAG
      
      - name: Debug push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          set -x
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/elBaguett/mntr.git
          git remote -v
          git fetch
          git status
          ls -la

      - name: Build & Push frontend
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ./manifests/frontend
          docker build -t $DOCKER_USER/mntr-frontend:$IMAGE_TAG .
          docker push $DOCKER_USER/mntr-frontend:$IMAGE_TAG

      - name: Build & Push db
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ./manifests/db
          docker build -t $DOCKER_USER/mntr-db:$IMAGE_TAG .
          docker push $DOCKER_USER/mntr-db:$IMAGE_TAG

      - name: Set up Git user and remotes
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "elBaguett"
          git config --global user.email "mme37005@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/elBaguett/mntr.git


      - name: Update Helm image tags for frontend, backend, db
        env: 
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sed -i "s/tag: frontend-.*/tag: frontend-${{ github.sha }}/" manifests/refactored/apps/frontend/values.yaml
          sed -i "s/tag: backend-.*/tag: backend-${{ github.sha }}/" manifests/refactored/apps/backend/values.yaml
          sed -i "s/tag: db-.*/tag: db-${{ github.sha }}/" manifests/refactored/apps/patroni/values.yaml

          git config --global user.name "elBaguett"
          git config --global user.email "mme37005@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/elBaguett/mntr.git
          git add manifests/refactored/apps/frontend/values.yaml \
                  manifests/refactored/apps/backend/values.yaml \
                  manifests/refactored/apps/patroni/values.yaml
          git commit -m "Update image tags to ${{ github.sha }}"
          git push origin main

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Generate SSH key for Terraform
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
