name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Lint & Tests 
        run: echo tests tbd

      - name: Docker Hub login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
        run: echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin

      - name: Build & Push backend
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t $DOCKER_USER/mntr-backend:$IMAGE_TAG .
          docker push $DOCKER_USER/mntr-backend:$IMAGE_TAG

      - name: Build & Push frontend
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          docker build -t $DOCKER_USER/mntr-frontend:$IMAGE_TAG .
          docker push $DOCKER_USER/mntr-frontend:$IMAGE_TAG

      - name: Build & Push db
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd db
          docker build -t $DOCKER_USER/mntr-db:$IMAGE_TAG .
          docker push $DOCKER_USER/mntr-db:$IMAGE_TAG

      - name: Update Helm image tag
        run: |
          sed -i "s/tag: .*/tag: ${{ github.sha }}/g" ./charts/my-app/values.yaml
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./charts/my-app/values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false